# ------------------------------------------------------------------------------
#  <auto-generated>
#      This code was generated by SpecFlow+ Excel (http://www.specflow.org/plus/Excel).
#      SpecFlow Version:2.1.0.0
#      SpecFlow+ Excel Version:1.4.2.0
#
#      SpecFlow+ Excel Evaluation Mode - Please purchase at http://www.specflow.org/plus.
# 
#      Changes to this file may cause incorrect behavior and will be lost if
#      the code is regenerated.
#  </auto-generated>
# ------------------------------------------------------------------------------

Feature: Calculator

Scenario: SpecFlow+ Excel Evaluation Mode
	* Please purchase at http://www.specflow.org/plus to remove this scenario.


Scenario: Add two numbers
	Given I have entered 50 Into the calculator
	And I have also entered 70 Into the calculator
	When i press add
	Then the result should be 120 on the screen


